///// <autogenerated>Remove this line to stop Code Generation</autogenerated>
///// <by>serverentity.txt</by>
///// <module>Gender</module>
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Gender.cs" company="Example">
//   The gender Entity
// </copyright>
// <summary>
//   The gender Entity.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Example.Data.Entities
{
    [Table("ml_gender")]
    public class Gender
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [Key, Required, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("gd_id")]
        [Display(Name = "Id")]
        public int Id
        {
            get;
            set;
        }

        /// _string_NOT_NULL_base
        /// <summary>
        /// Gets or sets the from title.
        /// </summary>
        [Column("gd_title"), Description("Title"), Required, MaxLength(200)]
        public string Title
        {
            get;
            set;
        }
    ////region CustomCodeBlock4#
    ////endregion CustomCodeBlock4#
    ////region CustomCodeBlock5#
    ////endregion CustomCodeBlock5#
    }
}