///// <autogenerated>Remove this line to stop Code Generation</autogenerated>
///// <by>servercollectionhelper.txt</by>
///// <module>CategoryHelper</module>
using Example.Data.Entities;
using Example.Models;

namespace Example.Business.Helpers
{
    //// className must ends with Helper
    //// Add pagename with postfix of Helper
    public static class CategoryHelper
    {
    }
}