///// <autogenerated>Remove this line to stop Code Generation</autogenerated>
///// <by>serverentity.txt</by>
///// <module>UserDetails</module>
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="UserDetails.cs" company="Example">
//   The user details Entity
// </copyright>
// <summary>
//   The user details Entity.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Example.Data.Entities
{
    [Table("ml_user")]
    public class User
    {
        /// _int_NULL_Foreign_base
        /// <summary>
        /// Gets or sets the created by.
        /// </summary>
        [Column("us_createdby"), Description("Created By"), ForeignKey("CreatedByRelation"), Range(int.MinValue, int.MaxValue)]
        public int? Createdby
        {
            get;
            set;
        }

        /// _string_NOT_NULL_base
        /// <summary>
        /// Gets or sets the from name.
        /// </summary>
        [Column("us_name"), Description("Name"), Required, MaxLength(100)]
        public string Name
        {
            get;
            set;
        }

        /// _string_NOT_NULL_base
        /// <summary>
        /// Gets or sets the from active directory id.
        /// </summary>
        [Column("us_ad_id"), Description("Active Directory Id"), Required, MaxLength(20)]
        public string AdId
        {
            get;
            set;
        }

        /// _string_NOT_NULL_base
        /// <summary>
        /// Gets or sets the from email.
        /// </summary>
        [Column("us_email"), Description("Email"), Required, MaxLength(300)]
        public string Email
        {
            get;
            set;
        }

        /// _string_NULL_base
        /// <summary>
        /// Gets or sets the password.
        /// </summary>
        [Column("us_password"), Description("Password"), MaxLength(500)]
        public string Password
        {
            get;
            set;
        }

        /// _int_NOT_NULL_base
        /// <summary>
        /// Gets or sets the employee id.
        /// </summary>
        [Column("us_employee_id"), Description("Employee Id"), Required, Range(int.MinValue, int.MaxValue)]
        public int EmployeeId
        {
            get;
            set;
        }

        /// _int_NOT_NULL_Foreign_base
        /// <summary>
        /// Gets or sets the role.
        /// </summary>
        [Column("us_role"), Description("Role"), ForeignKey("RoleRelation"), Range(int.MinValue, int.MaxValue)]
        public int Role
        {
            get;
            set;
        }

        /// _int_NULL_Foreign_base
        /// <summary>
        /// Gets or sets the created by.
        /// </summary>
        [Column("us_createdby"), Description("Created By"), ForeignKey("CreatedByRelation"), Range(int.MinValue, int.MaxValue)]
        public int? Createdby
        {
            get;
            set;
        }

        /// _DateTime_NULL_base
        /// <summary>
        /// Gets or sets the created date.
        /// </summary>
        [Column("us_createddate"), Description("Created Date")]
        public DateTime? Createddate
        {
            get;
            set;
        }

        /// _DateTime_NULL_base
        /// <summary>
        /// Gets or sets the modified date.
        /// </summary>
        [Column("us_modifieddate"), Description("Modified Date")]
        public DateTime? Modifieddate
        {
            get;
            set;
        }

        /// _int_NULL_base
        /// <summary>
        /// Gets or sets the commission rate.
        /// </summary>
        [Column("us_commissionrate"), Description("Commission Rate"), Range(int.MinValue, int.MaxValue)]
        public int? Commissionrate
        {
            get;
            set;
        }

        /// _int_NOT_NULL_Foreign_base
        /// <summary>
        /// Gets or sets the flag.
        /// </summary>
        [Column("us_reported"), Description("Flag"), ForeignKey("FlagRelation"), Range(int.MinValue, int.MaxValue)]
        public int Flag
        {
            get;
            set;
        }

        /// _string_NULL_base
        /// <summary>
        /// Gets or sets the logo.
        /// </summary>
        [Column("us_logo"), Description("Logo"), MaxLength(500)]
        public string Logo
        {
            get;
            set;
        }

        /// _int_NOT_NULL_Foreign_base
        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        [Column("us_status"), Description("Status"), ForeignKey("StatusRelation"), Range(int.MinValue, int.MaxValue)]
        public int Status
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [Key, Required, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("us_id")]
        [Display(Name = "Id")]
        public int Id
        {
            get;
            set;
        }

        /// _DateTime_NULL_base
        /// <summary>
        /// Gets or sets the modified date.
        /// </summary>
        [Column("us_modifieddate"), Description("Modified Date")]
        public DateTime? Modifieddate
        {
            get;
            set;
        }

        /// _int_NULL_base
        /// <summary>
        /// Gets or sets the commission rate.
        /// </summary>
        [Column("us_commissionrate"), Description("Commission Rate"), Range(int.MinValue, int.MaxValue)]
        public int? Commissionrate
        {
            get;
            set;
        }

        /// _int_NOT_NULL_Foreign_base
        /// <summary>
        /// Gets or sets the flag.
        /// </summary>
        [Column("us_reported"), Description("Flag"), ForeignKey("FlagRelation"), Range(int.MinValue, int.MaxValue)]
        public int Flag
        {
            get;
            set;
        }

        /// _string_NULL_base
        /// <summary>
        /// Gets or sets the logo.
        /// </summary>
        [Column("us_logo"), Description("Logo"), MaxLength(500)]
        public string Logo
        {
            get;
            set;
        }

        /// _int_NOT_NULL_Foreign_base
        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        [Column("us_status"), Description("Status"), ForeignKey("StatusRelation"), Range(int.MinValue, int.MaxValue)]
        public int Status
        {
            get;
            set;
        }

        /// _string_NOT_NULL_base
        /// <summary>
        /// Gets or sets the from name.
        /// </summary>
        [Column("us_name"), Description("Name"), Required, MaxLength(100)]
        public string Name
        {
            get;
            set;
        }

        /// _string_NOT_NULL_base
        /// <summary>
        /// Gets or sets the from active directory id.
        /// </summary>
        [Column("us_ad_id"), Description("Active Directory Id"), Required, MaxLength(20)]
        public string AdId
        {
            get;
            set;
        }

        /// _string_NOT_NULL_base
        /// <summary>
        /// Gets or sets the from email.
        /// </summary>
        [Column("us_email"), Description("Email"), Required, MaxLength(300)]
        public string Email
        {
            get;
            set;
        }

        /// _string_NULL_base
        /// <summary>
        /// Gets or sets the password.
        /// </summary>
        [Column("us_password"), Description("Password"), MaxLength(500)]
        public string Password
        {
            get;
            set;
        }

        /// _int_NOT_NULL_base
        /// <summary>
        /// Gets or sets the employee id.
        /// </summary>
        [Column("us_employee_id"), Description("Employee Id"), Required, Range(int.MinValue, int.MaxValue)]
        public int EmployeeId
        {
            get;
            set;
        }

        /// _int_NOT_NULL_Foreign_base
        /// <summary>
        /// Gets or sets the role.
        /// </summary>
        [Column("us_role"), Description("Role"), ForeignKey("RoleRelation"), Range(int.MinValue, int.MaxValue)]
        public int Role
        {
            get;
            set;
        }

        /// _DateTime_NULL_base
        /// <summary>
        /// Gets or sets the created date.
        /// </summary>
        [Column("us_createddate"), Description("Created Date")]
        public DateTime? Createddate
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [Key, Required, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("us_id")]
        [Display(Name = "Id")]
        public int Id
        {
            get;
            set;
        }

        ////region CustomCodeBlock4#
        ////endregion CustomCodeBlock4#
        public virtual User CreatedByRelation
        {
            get;
            set;
        }

        public virtual UserRole RoleRelation
        {
            get;
            set;
        }

        public virtual User CreatedByRelation
        {
            get;
            set;
        }

        public virtual Status FlagRelation
        {
            get;
            set;
        }

        public virtual Status StatusRelation
        {
            get;
            set;
        }

        public virtual Status FlagRelation
        {
            get;
            set;
        }

        public virtual Status StatusRelation
        {
            get;
            set;
        }

        public virtual UserRole RoleRelation
        {
            get;
            set;
        }
    ////region CustomCodeBlock5#
    ////endregion CustomCodeBlock5#
    }
}