///// <autogenerated>Remove this line to stop Code Generation</autogenerated>
///// <by>serverenum.txt</by>
///// <module>Category</module>
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Category.cs" company="Example">
//   The category Enums
// </copyright>
// <summary>
//   The category Enums.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
using System.ComponentModel;

namespace Example.Models.Enums
{
    public enum CategoryEnum
    {
        [Description("Category 1")]
        Category_1 = 1,
        [Description("category desc")]
        category_desc = 1,
    }
}