///// <autogenerated>Remove this line to stop Code Generation</autogenerated>
///// <by>serverenum.txt</by>
///// <module>Gender</module>
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Gender.cs" company="Example">
//   The gender Enums
// </copyright>
// <summary>
//   The gender Enums.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
using System.ComponentModel;

namespace Example.Models.Enums
{
    public enum GenderEnum
    {
        [Description("Male")]
        Male = 1,
        [Description("Female")]
        Female = 2,
    }
}