///// <autogenerated>Remove this line to stop Code Generation</autogenerated>
///// <by>serveriservice.txt</by>
///// <module>Category</module>
using System.Collections.Generic;
using Example.Models;
using Example.Models.Common;

namespace Example.Business.Contracts
{
    public interface ICategoryService
    {
        GetResponseModel<CategoryModel> Get(CategoryModel model);
        RawResponseModel<CategoryModel> Save(CategoryModel model);
        DeleteResponseModel Delete(CategoryModel model);
    }
}