///// <autogenerated>Remove this line to stop Code Generation<autogenerated>
using Example.Data.Entities;
using Microsoft.EntityFrameworkCore;
using System;

namespace Example.Entities
{
    /// <summary>
    /// ExampleDbContext class
    /// </summary>
    public class ExampleDbContext : DbContext
    {
        //// region ModuleListEntity#
        public virtual DbSet<UserRole> UserRole
        {
            get;
            set;
        }

        public virtual DbSet<UserDetails> UserDetails
        {
            get;
            set;
        }

        public virtual DbSet<TicketStatus> TicketStatus
        {
            get;
            set;
        }

        public virtual DbSet<TicketMaster> TicketMaster
        {
            get;
            set;
        }

        public virtual DbSet<TicketLog> TicketLog
        {
            get;
            set;
        }

        public virtual DbSet<ComplaintType> ComplaintType
        {
            get;
            set;
        }

        //// endregion ModuleListEntity#       
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }

        public ExampleDbContext(DbContextOptions<ExampleDbContext> options): base(options)
        {
        }
    }
}