///// <autogenerated>Remove this line to stop Code Generation</autogenerated>
///// <by>servermodel.txt</by>
///// <module>Gender</module>
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="GenderModel.cs" company="Example">
//   The gender Model
// </copyright>
// <summary>
//   The gender Model.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Example.Models
{
    public class GenderModel
    {
        ////region CustomCodeBlock1#
        ////endregion CustomCodeBlock1#
        /// _int_Primary_selected
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [Key, Display(Name = "Id")]
        public int Id
        {
            get;
            set;
        }

        /// _string_NOT_NULL_selected
        /// <summary>
        /// Gets or sets the from title.
        /// </summary>
        [Display(Name = "Title"), StringLength(200)]
        public string Title
        {
            get;
            set;
        }
    }
}