///// <autogenerated>Remove this line to stop Code Generation</autogenerated>
///// <by>serveriservice.txt</by>
///// <module>Gender</module>
using System.Collections.Generic;
using Example.Models;
using Example.Models.Common;

namespace Example.Business.Contracts
{
    public interface IGenderService
    {
        GetResponseModel<GenderModel> Get(GenderModel model, PaginationModel paginationModel = null, SortModel sortModel = null);
        RawResponseModel<GenderModel> Save(GenderModel model);
        DeleteResponseModel Delete(GenderModel model);
    }
}